### ISSUE TITLE
发送translate指令似乎没用了

### ISSUE THREAD

**Issue by yi03** [koishijs/translator#6]
所有插件都是最新版，填写了App Key和Secret。
发送help能看到translate指令，但是发送translate没有反应。

**Comment by shigma** [comment]
看看报错？

**Comment by yi03** [comment]
> 看看报错？

```
2023-06-01 23:48:05 [W] sqlite > SELECT  FROM `channel` kodsfdfv WHERE `platform` = 'onebot' AND `id` = '767320659'
2023-06-01 23:48:05 [W] session translate hi
                        Error: near "FROM": syntax error
                            at f.handleError (C:\Users\46516\koishi-bot\koishi-app10\node_modules\@minatojs\sql.js\dist\sql-wasm.js:91:290)
                            at f.prepare (C:\Users\46516\koishi-bot\koishi-app10\node_modules\@minatojs\sql.js\dist\sql-wasm.js:90:46)
                            at #exec (C:\Users\46516\koishi-bot\koishi-app10\node_modules\@minatojs\driver-sqlite\lib\index.js:347:26)
                            at #all (C:\Users\46516\koishi-bot\koishi-app10\node_modules\@minatojs\driver-sqlite\lib\index.js:359:48)
                            at SQLiteDriver.get (C:\Users\46516\koishi-bot\koishi-app10\node_modules\@minatojs\driver-sqlite\lib\index.js:286:54)
                            at Selection.execute (C:\Users\46516\koishi-bot\koishi-app10\node_modules\@minatojs\core\lib\index.cjs:384:34)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async DatabaseService.getChannel (C:\Users\46516\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:393:18)
                            at async Session2.getChannel (C:\Users\46516\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:2022:21)
                            at async Session2._observeChannelLike (C:\Users\46516\koishi-bot\koishi-app10\node_modules\@koishijs\core\lib\index.cjs:2047:18)
```

**Comment by shigma** [comment]
这是唯一的报错吗？看起来这些错误与 translator 插件无关，是你升级炸了或者其他插件的问题。

**Comment by yi03** [comment]
> 这是唯一的报错吗？看起来这些错误与 translator 插件无关，是你升级炸了或者其他插件的问题。

是唯一的报错。
这样啊，不好意思打扰了。最近睡眠不足有点晕晕的。

**Comment by yi03** [comment]
> 这是唯一的报错吗？看起来这些错误与 translator 插件无关，是你升级炸了或者其他插件的问题。

不对。我今天开了一个新项目，只装了translator-youdao这一个插件，然后在沙盒里发送translate hi，还是报一样的错。
```
2023-06-03 11:08:51 [I] app apply plugin translator-youdao:gct4am
2023-06-03 11:09:00 [W] sqlite > SELECT  FROM `channel` blgnjrfg WHERE `platform` = 'sandbox:gybx7il6l' AND `id` = '#'
2023-06-03 11:09:00 [W] session translate hi
                        Error: near "FROM": syntax error
                            at f.handleError (C:\Users\45137\koishi-bot\koishi-app15\node_modules\@minatojs\sql.js\dist\sql-wasm.js:91:290)
                            at f.prepare (C:\Users\45137\koishi-bot\koishi-app15\node_modules\@minatojs\sql.js\dist\sql-wasm.js:90:46)
                            at #exec (C:\Users\45137\koishi-bot\koishi-app15\node_modules\@minatojs\driver-sqlite\lib\index.js:347:26)
                            at #all (C:\Users\45137\koishi-bot\koishi-app15\node_modules\@minatojs\driver-sqlite\lib\index.js:359:48)
                            at SQLiteDriver.get (C:\Users\45137\koishi-bot\koishi-app15\node_modules\@minatojs\driver-sqlite\lib\index.js:286:54)
                            at Selection.execute (C:\Users\45137\koishi-bot\koishi-app15\node_modules\@minatojs\core\lib\index.cjs:384:34)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async DatabaseService.getChannel (C:\Users\45137\koishi-bot\koishi-app15\node_modules\@koishijs\core\lib\index.cjs:393:18)
                            at async Session2.getChannel (C:\Users\45137\koishi-bot\koishi-app15\node_modules\@koishijs\core\lib\index.cjs:2022:21)
                            at async Session2._observeChannelLike (C:\Users\45137\koishi-bot\koishi-app15\node_modules\@koishijs\core\lib\index.cjs:2047:18)
```

**Comment by Alirea10** [comment]
![image](https://github.com/koishijs/translator/assets/111880868/794f6b2a-8a2f-4c74-9f01-a636077e74a4)
我还尝试了open-translate，也是同样的报错，初步猜测以上插件都受到影响，可能和“服务”有关
附上https://forum.koishi.xyz/t/topic/2808 的部分插件版本内容
"@koishijs/plugin-console": "5.11.1",
"koishi": "4.13.2",
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Binaries:
    Node: 16.19.1
    Yarn: 3.5.0
Koishi:
    Core: 4.13.2
    Console: 5.11.1
    Koishi Desktop: 0.10.5

**Comment by shigma** [comment]
已确认问题并修复。
